
export const proposalRejections = [
    {
        id: 'deadlineNotMet',
        title: 'Deadline for submission was not met.',
    },
    {
        id: 'unclearCosting',
        title: 'Unclear cost breakdown.'
    },
    {
        id: 'unattractiveContent',
        title: 'Course content is not attractive or informative.'
    },
    {
        id: 'lackDifferentiation',
        title: 'Lack differentiation from the competition.'
    },
    {
        id: 'incomplete',
        title: 'Proposal Is incomplete or not as expected.'
    },
    {
        id: 'other',
        title: 'Others'
    }
]

export let proposals = [
    {
        title: 'Course A',
        id: '11111',
        courseCode: 'CC101',
        organisationName: 'Test Company',
        type: 'Short Courses',
        category: "IT & Science",
        format: 'F2F/Online',
        totalDuration: 5,
        totalSessions: 5,
        skillsFutureEligible: true,
        fullCourseFee: 1000,
        GSTOfFullCourseFee: 1070,
        subsidyPerPax: 800,
        createdDate: '19/09/2022',
        courseFeePerPax: 200,
        status: 'draft',
        remark: '',
        description: '',
        objectives: '',
        learningOutcomes: '',
        topicsCovered: '',
        trainingDeliveryMethods: '',
        trainers: [{
            id: 111,
            name: 'Adam Chua',
            profile: 'This is profile of Adam',
            attended: 1,
            source: 'External'
        }, {
            id: 112,
            name: 'Celine Chan',
            profile: 'This is profile of Celine.',
            attended: 0,
            source: 'In-house'
        }],
        maxClassSize: 20,
        trainerNo: 2,
        trainerUnitCost: 100.00,
        trainerHours: 5.00,
        trainerTotal: 1000.00,
        facilitatorNo: 2,
        facilitatorUnitCost: 50.00,
        facilitatorHours: 5,
        facilitatorTotal: 500.00,
        manpowerNo: 5,
        manpowerUnitCost: 50.00,
        manpowerHours: 5,
        manpowerTotal: 1250.00,
        manpowerRemark: 'This is manpower remark',
        venueNo: 1,
        venueUnitCost: 500.00,
        venueHours: 5,
        venueTotal: 2500.00,
        publicityUnitCost: 0,
        publicityTotal: 0,
        logisticUnitCost: 0,
        logisticTotal: 0,
        logisticRemark: '',
        transportUnitCost: 0,
        transportTotal: 0,
        othersNo: 0,
        othersUnitCost: 0,
        othersHours: 0,
        othersTotal: 0,
        othersRemark: '',
        ccNo: 0,
        ccUnitCost: 0,
        ccTotal: 0,
        ccRemark: 'Please elaborate',
        trainingNo: 0,
        trainingUnitCost: 0,
        trainingTotal: 0,
        places: 0,
        partATotal: 5000.00,
        partBTotal: 5000.00,
        total: 10000.00,
        fullCoursePerPax: 2000.00,

    },
    {
        title: 'Course B',
        id: '11112',
        courseCode: 'CC102',
        organisationName: 'Test Company',
        type: 'Short Courses',
        category: "IT & Science",
        format: 'F2F/Online',
        totalDuration: 5,
        totalSessions: 5,
        skillsFutureEligible: true,
        fullCourseFee: 3000,
        GSTOfFullCourseFee: 1070,
        subsidyPerPax: 550,
        createdDate: '19/09/2022',
        courseFeePerPax: 200,
        status: 'pendingClarification',
        remark: '',
        description: '',
        objectives: '',
        learningOutcomes: '',
        topicsCovered: '',
        trainingDeliveryMethods: '',
        trainers: [],
        maxClassSize: 20,
        trainerNo: 2,
        trainerUnitCost: 100.00,
        trainerHours: 5.00,
        trainerTotal: 1000.00,
        facilitatorNo: 2,
        facilitatorUnitCost: 50.00,
        facilitatorHours: 5,
        facilitatorTotal: 500.00,
        manpowerNo: 5,
        manpowerUnitCost: 50.00,
        manpowerHours: 5,
        manpowerTotal: 1250.00,
        manpowerRemark: 'This is manpower remark',
        venueNo: 1,
        venueUnitCost: 500.00,
        venueHours: 5,
        venueTotal: 2500.00,
        publicityUnitCost: 0,
        publicityTotal: 0,
        logisticUnitCost: 0,
        logisticTotal: 0,
        logisticRemark: '',
        transportUnitCost: 0,
        transportTotal: 0,
        othersNo: 0,
        othersUnitCost: 0,
        othersHours: 0,
        othersTotal: 0,
        othersRemark: '',
        ccNo: 0,
        ccUnitCost: 0,
        ccTotal: 0,
        ccRemark: 'Please elaborate',
        trainingNo: 0,
        trainingUnitCost: 0,
        trainingTotal: 0,
        places: 0,
        partATotal: 5000.00,
        partBTotal: 5000.00,
        total: 10000.00,
        fullCoursePerPax: 2000.00,
        clarification: 'Your course has costs on trainers but there are no trainer details and CV being provided. Please clarify as soon as possible. Thanks'

    },
    {
        title: 'Course C',
        id: '11113',
        courseCode: 'CC103',
        organisationName: 'Test Company',
        type: 'Short Courses',
        category: "IT & Science",
        format: 'F2F/Online',
        totalDuration: 5,
        totalSessions: 5,
        skillsFutureEligible: true,
        fullCourseFee: 2400,
        GSTOfFullCourseFee: 1070,
        subsidyPerPax: 600,
        createdDate: '19/09/2022',
        courseFeePerPax: 200,
        status: 'approved',
        remark: '',
        description: '',
        objectives: '',
        learningOutcomes: '',
        topicsCovered: '',
        trainingDeliveryMethods: '',
        trainers: [{
            id: 111,
            name: 'Adam Chua',
            profile: 'This is profile of Adam',
            attended: 1,
            source: 'External'
        },
            {
            id: 112,
            name: 'Celine Chan',
            profile: 'This is profile of Celine.',
            attended: 0,
            source: 'In-house'
        }],
        maxClassSize: 20,
        trainerNo: 2,
        trainerUnitCost: 100.00,
        trainerHours: 5.00,
        trainerTotal: 1000.00,
        facilitatorNo: 2,
        facilitatorUnitCost: 50.00,
        facilitatorHours: 5,
        facilitatorTotal: 500.00,
        manpowerNo: 5,
        manpowerUnitCost: 50.00,
        manpowerHours: 5,
        manpowerTotal: 1250.00,
        manpowerRemark: 'This is manpower remark',
        venueNo: 1,
        venueUnitCost: 500.00,
        venueHours: 5,
        venueTotal: 2500.00,
        publicityUnitCost: 0,
        publicityTotal: 0,
        logisticUnitCost: 0,
        logisticTotal: 0,
        logisticRemark: '',
        transportUnitCost: 0,
        transportTotal: 0,
        othersNo: 0,
        othersUnitCost: 0,
        othersHours: 0,
        othersTotal: 0,
        othersRemark: '',
        ccNo: 0,
        ccUnitCost: 0,
        ccTotal: 0,
        ccRemark: 'Please elaborate',
        trainingNo: 0,
        trainingUnitCost: 0,
        trainingTotal: 0,
        places: 0,
        partATotal: 5000.00,
        partBTotal: 5000.00,
        total: 10000.00,
        fullCoursePerPax: 2000.00,
        fundingLevel: 10000.00,
    },
    {
        title: 'Course D',
        id: '11114',
        courseCode: 'CC104',
        organisationName: 'Test Company',
        type: 'Short Courses',
        category: "IT & Science",
        format: 'F2F/Online',
        totalDuration: 5,
        totalSessions: 5,
        skillsFutureEligible: true,
        fullCourseFee: 1000,
        GSTOfFullCourseFee: 1070,
        createdDate: '19/09/2022',
        courseFeePerPax: 200,
        status: 'published',
        remark: '',
        description: '',
        objectives: '',
        learningOutcomes: '',
        topicsCovered: '',
        trainingDeliveryMethods: '',
        trainers: [{
            id: 111,
            name: 'Adam Chua',
            profile: 'This is profile of Adam',
            attended: 1,
            source: 'External'
        },
            {
            id: 112,
            name: 'Celine Chan',
            profile: 'This is profile of Celine.',
            attended: 0,
            source: 'In-house'
        }],
        maxClassSize: 20,
        trainerNo: 2,
        trainerUnitCost: 100.00,
        trainerHours: 5.00,
        trainerTotal: 1000.00,
        facilitatorNo: 2,
        facilitatorUnitCost: 50.00,
        facilitatorHours: 5,
        facilitatorTotal: 500.00,
        manpowerNo: 5,
        manpowerUnitCost: 50.00,
        manpowerHours: 5,
        manpowerTotal: 1250.00,
        manpowerRemark: 'This is manpower remark',
        venueNo: 1,
        venueUnitCost: 500.00,
        venueHours: 5,
        venueTotal: 2500.00,
        publicityUnitCost: 0,
        publicityTotal: 0,
        logisticUnitCost: 0,
        logisticTotal: 0,
        logisticRemark: '',
        transportUnitCost: 0,
        transportTotal: 0,
        othersNo: 0,
        othersUnitCost: 0,
        othersHours: 0,
        othersTotal: 0,
        othersRemark: '',
        ccNo: 0,
        ccUnitCost: 0,
        ccTotal: 0,
        ccRemark: 'Please elaborate',
        trainingNo: 0,
        trainingUnitCost: 0,
        trainingTotal: 0,
        places: 0,
        partATotal: 5000.00,
        partBTotal: 5000.00,
        total: 10000.00,
        fullCoursePerPax: 2000.00,
        fundingLevel: 8000.00,
    },
    {
        title: 'Course E',
        id: '11115',
        courseCode: 'CC105',
        organisationName: 'Test Company',
        type: 'Short Courses',
        category: "IT & Science",
        format: 'F2F/Online',
        totalDuration: 5,
        totalSessions: 5,
        skillsFutureEligible: true,
        fullCourseFee: 1000,
        GSTOfFullCourseFee: 1070,
        createdDate: '19/09/2022',
        courseFeePerPax: 200,
        status: 'rejected',
        remark: '',
        description: '',
        objectives: '',
        learningOutcomes: '',
        topicsCovered: '',
        trainingDeliveryMethods: '',
        trainers: [{
            id: 111,
            name: 'Adam Chua',
            profile: 'This is profile of Adam',
            attended: 1,
            source: 'External'
        },
            {
                id: 112,
                name: 'Celine Chan',
                profile: 'This is profile of Celine.',
                attended: 0,
                source: 'In-house'
            }],
        maxClassSize: 20,
        trainerNo: 2,
        trainerUnitCost: 100.00,
        trainerHours: 5.00,
        trainerTotal: 1000.00,
        facilitatorNo: 2,
        facilitatorUnitCost: 50.00,
        facilitatorHours: 5,
        facilitatorTotal: 500.00,
        manpowerNo: 5,
        manpowerUnitCost: 50.00,
        manpowerHours: 5,
        manpowerTotal: 1250.00,
        manpowerRemark: 'This is manpower remark',
        venueNo: 1,
        venueUnitCost: 500.00,
        venueHours: 5,
        venueTotal: 2500.00,
        publicityUnitCost: 0,
        publicityTotal: 0,
        logisticUnitCost: 0,
        logisticTotal: 0,
        logisticRemark: '',
        transportUnitCost: 0,
        transportTotal: 0,
        othersNo: 0,
        othersUnitCost: 0,
        othersHours: 0,
        othersTotal: 0,
        othersRemark: '',
        ccNo: 0,
        ccUnitCost: 0,
        ccTotal: 0,
        ccRemark: 'Please elaborate',
        trainingNo: 0,
        trainingUnitCost: 0,
        trainingTotal: 0,
        places: 0,
        partATotal: 5000.00,
        partBTotal: 5000.00,
        total: 10000.00,
        fullCoursePerPax: 2000.00,
        rejection: 'deadlineNotMet'
    },
    {
        title: 'Course F',
        id: '11116',
        courseCode: 'CC106',
        organisationName: 'Test Company',
        type: 'Short Courses',
        category: "IT & Science",
        format: 'F2F/Online',
        totalDuration: 5,
        totalSessions: 5,
        skillsFutureEligible: true,
        fullCourseFee: 1000,
        GSTOfFullCourseFee: 1070,
        createdDate: '19/09/2022',
        courseFeePerPax: 200,
        remark: '',
        description: '',
        objectives: '',
        learningOutcomes: '',
        topicsCovered: '',
        trainingDeliveryMethods: '',
        trainers: [{
            id: 111,
            name: 'Adam Chua',
            profile: 'This is profile of Adam',
            attended: 1,
            source: 'External'
        },
            {
                id: 112,
                name: 'Celine Chan',
                profile: 'This is profile of Celine.',
                attended: 0,
                source: 'In-house'
            }],
        maxClassSize: 20,
        trainerNo: 2,
        trainerUnitCost: 100.00,
        trainerHours: 5.00,
        trainerTotal: 1000.00,
        facilitatorNo: 2,
        facilitatorUnitCost: 50.00,
        facilitatorHours: 5,
        facilitatorTotal: 500.00,
        manpowerNo: 5,
        manpowerUnitCost: 50.00,
        manpowerHours: 5,
        manpowerTotal: 1250.00,
        manpowerRemark: 'This is manpower remark',
        venueNo: 1,
        venueUnitCost: 500.00,
        venueHours: 5,
        venueTotal: 2500.00,
        publicityUnitCost: 0,
        publicityTotal: 0,
        logisticUnitCost: 0,
        logisticTotal: 0,
        logisticRemark: '',
        transportUnitCost: 0,
        transportTotal: 0,
        othersNo: 0,
        othersUnitCost: 0,
        othersHours: 0,
        othersTotal: 0,
        othersRemark: '',
        ccNo: 0,
        ccUnitCost: 0,
        ccTotal: 0,
        ccRemark: 'Please elaborate',
        trainingNo: 0,
        trainingUnitCost: 0,
        trainingTotal: 0,
        places: 0,
        partATotal: 5000.00,
        partBTotal: 5000.00,
        total: 10000.00,
        fullCoursePerPax: 2000.00,
        status: 'pendingApproval',
    },
    {
        "title": "Be an Instagrammer",
        "id": "CC1",
        "courseCode": "CC1",
        "organisationName": "Simple IT!",
        "type": "Short Courses",
        "category": "IT & Science",
        "format": "F2F/Online",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 410.00,
        "GSTOfFullCourseFee": 438.70,
        "subsidyPerPax": 400.00,
        "createdDate": "19/09/2022",
        "courseFeePerPax": 10.00,
        "status": "draft",
        "trainers": [
            {
                id: Date.now(),
                name: 'Adam Chua',
                profile: 'Adam is a professional instructor.',
                attended: 1,
                source: 'External'
            },
            {
                id: Date.now(),
                name: 'Celine Chan',
                profile: 'Celine is has a Bachelor Degree in Information Technology.',
                attended: 0,
                source: 'In-house'
            }
        ]
    },
    {
        "title": "Facebook",
        "id": "CC2",
        "courseCode": "CC2",
        "organisationName": "Simple IT!",
        "type": "Short Courses",
        "category": "IT & Science",
        "format": "F2F/Online",
        "totalDuration": 4,
        "totalSessions": 2,
        "skillsFutureEligible": true,
        "fullCourseFee": 510.00,
        "GSTOfFullCourseFee": 545.70,
        "subsidyPerPax": 500.00,
        "createdDate": "19/09/2022",
        "courseFeePerPax": 10.00,
        "status": "pendingApproval",
    },
    {
        "title": "Adopting Growth Mindset to Improve Learning, Ability, and Inner Motivation",
        "id": "CC3",
        "courseCode": "CC3",
        "organisationName": "Nanyang Technological University (NTU)",
        "type": "Short Courses",
        "category": "Ageing & Life Skills",
        "format": "F2F/Online",
        "totalDuration": 6,
        "totalSessions": 3,
        "skillsFutureEligible": true,
        "fullCourseFee": 410.00,
        "GSTOfFullCourseFee": 438.70,
        "subsidyPerPax": 400.00,
        "createdDate": "19/09/2022",
        "courseFeePerPax": 10.00,
        "status": "pendingClarification",
        "clarification": 'Your course has costs on trainers but there are no trainer details and CV being provided. Please clarify as soon as possible. Thanks'
    },
    {
        "title": "Mindful Farming (Malay) Berkebun Dengan Amalan Kesedaran",
        "id": "CC4",
        "courseCode": "CC4",
        "organisationName": "Social Innovation Park (SIP)",
        "type": "Short Courses",
        "category": "Ageing & Life Skills",
        "format": "F2F/Online",
        "totalDuration": 5,
        "totalSessions": 2,
        "skillsFutureEligible": false,
        "fullCourseFee": 384.00,
        "GSTOfFullCourseFee": 410.88,
        "subsidyPerPax": 300.00,
        "createdDate": "19/09/2022",
        "courseFeePerPax": 84.00,
        "status": "approved",
        "funding": 20000,
    },
    {
        "title": "Uniquely Singapore Kopi Set",
        "id": "CC5",
        "courseCode": "CC5",
        "organisationName": "Project Dignity Pte Ltd",
        "type": "Short Courses",
        "category": "Ageing & Life Skills",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 322.95,
        "GSTOfFullCourseFee": 345.56,
        "subsidyPerPax": 300.00,
        "createdDate": "19/09/2022",
        "courseFeePerPax": 22.95,
        "status": "rejected",
    },
    {
        "title": "Auditing for Non-Auditors",
        "id": "CC6",
        "courseCode": "CC6",
        "organisationName": "Singapore Professionals’ and Executives’ Co-operative (SPEC)",
        "type": "Short Courses",
        "category": "Finance & Business",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 890.00,
        "GSTOfFullCourseFee": 952.30,
        "subsidyPerPax": 800.00,
        "createdDate": "19/09/2022",
        "courseFeePerPax": 90.00,
        "status": "published",
        "funding": 20000,
    },
    {
        "title": "Seniorpreneurship",
        "id": "CC7",
        "courseCode": "CC7",
        "organisationName": "Singapore Training & Development Association",
        "type": "Short Courses",
        "category": "Finance & Business",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 540.00,
        "GSTOfFullCourseFee": 577.80,
        "subsidyPerPax": 500.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 40.00
    },
    {            "title": "Cultivate your health with Chinese Medicine (Conducted Online)",
        "id": "CC8",
        "courseCode": "CC8",
        "organisationName": "Renhai Centre",
        "type": "Bite-Sized Courses",
        "category": "Health & Wellness",
        "format": "F2F/Online",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 510.00,
        "GSTOfFullCourseFee": 545.70,
        "subsidyPerPax": 500.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 10.00
    },
    {            "title": "Starting a Home Business Using Business Model Canvas",
        "id": "CC9",
        "courseCode": "CC9",
        "organisationName": "Institute of Technical Education (ITE)",
        "type": "Bite-Sized Courses",
        "category": "Finance & Business",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 310.00,
        "GSTOfFullCourseFee": 331.70,
        "subsidyPerPax": 300.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 10.00
    },
    {
        "title": "Introduction to Electric Vehicle",
        "id": "CC10",
        "courseCode": "CC10",
        "organisationName": "Ngee Ann Polytechnic",
        "type": "Bite-Sized Courses",
        "category": "IT & Science",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 610.00,
        "GSTOfFullCourseFee": 652.70,
        "subsidyPerPax": 600.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 10.00
    },
    {
        "title": "Managing Your Personal Finances\r",
        "id": "CC11",
        "courseCode": "CC11",
        "organisationName": "Singapore University of Social Sciences (SUSS)",
        "type": "Exam Free Courses",
        "category": "Ageing & Life Skills",
        "format": "Blended",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 250.00,
        "GSTOfFullCourseFee": 267.50,
        "subsidyPerPax": 213.08,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 36.92
    },
    {
        "title": "Elements of Conveyancing Practice\r\n",
        "id": "CC12",
        "courseCode": "CC12",
        "organisationName": "Singapore University of Social Sciences (SUSS)",
        "type": "Exam Free Courses",
        "category": "Finance & Business",
        "format": "F2F/Online",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 660.50,
        "GSTOfFullCourseFee": 706.74,
        "subsidyPerPax": 500.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 160.50
    },
    {
        "title": "Management",
        "id": "CC13",
        "courseCode": "CC13",
        "organisationName": "Singapore University of Social Sciences (SUSS)",
        "type": "Exam Free Courses",
        "category": "Finance & Business",
        "format": "F2F/Online",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 673.72,
        "GSTOfFullCourseFee": 720.88,
        "subsidyPerPax": 600.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 73.72
    },
    {
        "title": "TCM: A Primer Course",
        "id": "CC14",
        "courseCode": "CC14",
        "organisationName": "Nanyang Technological University (NTU)",
        "type": "Exam Free Courses",
        "category": "Health & Wellness",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 813.83,
        "GSTOfFullCourseFee": 870.80,
        "subsidyPerPax": 700.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 113.83
    },
    {
        "title": "Understanding Poems and Plays",
        "id": "CC15",
        "courseCode": "CC15",
        "organisationName": "Singapore University of Social Sciences (SUSS)",
        "type": "Exam Free Courses",
        "category": "Humanities",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 573.72,
        "GSTOfFullCourseFee": 613.88,
        "subsidyPerPax": 500.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 73.72
    },
    {
        "title": "Communication Across Cultural Context\r",
        "id": "CC16",
        "courseCode": "CC16",
        "organisationName": "Nanyang Technological University (NTU)\r\n\r",
        "type": "Exam Free Courses",
        "category": "Humanities",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 713.83,
        "GSTOfFullCourseFee": 763.80,
        "subsidyPerPax": 600.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 113.83
    },
    {
        "title": "How to Use Carousell (Conducted Online)\r",
        "id": "CC17",
        "courseCode": "CC17",
        "organisationName": "Family Central",
        "type": "Intergenerational Learning Programme",
        "category": "Finance & Business",
        "format": "F2F/Online",
        "totalDuration": 6,
        "totalSessions": 3,
        "skillsFutureEligible": false,
        "fullCourseFee": 300.00,
        "GSTOfFullCourseFee": 321.00,
        "subsidyPerPax": 300.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 0.00
    },
    {
        "title": "Upcycle and Save the Earth (Conducted Online)\r",
        "id": "CC18",
        "courseCode": "CC18",
        "organisationName": "Family Central",
        "type": "Intergenerational Learning Programme",
        "category": "Humanities",
        "format": "F2F/Online",
        "totalDuration": 11,
        "totalSessions": 4,
        "skillsFutureEligible": false,
        "fullCourseFee": 700.00,
        "GSTOfFullCourseFee": 749.00,
        "subsidyPerPax": 700.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 0.00
    },
    {
        "title": "Fun with Telegram (Conducted Online)\r",
        "id": "CC19",
        "courseCode": "CC19",
        "organisationName": "Family Central",
        "type": "Intergenerational Learning Programme",
        "category": "IT & Science",
        "format": "F2F/Online",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 400.00,
        "GSTOfFullCourseFee": 428.00,
        "subsidyPerPax": 400.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 0.00
    },
    {
        "title": "Vietnamese Level 5 (Conducted Online)\r",
        "id": "CC20",
        "courseCode": "CC20",
        "organisationName": "National University of Singapore (NUS)",
        "type": "Short Courses",
        "category": "Humanities",
        "format": "F2F/Online",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 1042.00,
        "GSTOfFullCourseFee": 1114.94,
        "subsidyPerPax": 700.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 342.00
    },
    {
        "title": "Spanish Level 5 (Conducted Online)\r",
        "id": "CC21",
        "courseCode": "CC21",
        "organisationName": "National University of Singapore (NUS)",
        "type": "Short Courses",
        "category": "Humanities",
        "format": "F2F/Online",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 842.00,
        "GSTOfFullCourseFee": 900.94,
        "subsidyPerPax": 500.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 342.00
    },
    {
        "title": "Cryptocurrency and Blockchain – Understanding the Opportunity and Risks",
        "id": "CC22",
        "courseCode": "CC22",
        "organisationName": "National University of Singapore Society (NUSS)",
        "type": "Short Courses",
        "category": "IT & Science",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 253.46,
        "GSTOfFullCourseFee": 271.20,
        "subsidyPerPax": 200.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 53.46
    },
    {
        "title": "Build Lower Body Strength with Workout & Dance\r\n",
        "id": "CC23",
        "courseCode": "CC23",
        "organisationName": "Singapore Association for Continuing Education (SACE)",
        "type": "Short Courses",
        "category": "Media Arts & Design",
        "format": "F2F only",
        "totalDuration": 9,
        "totalSessions": 3,
        "skillsFutureEligible": true,
        "fullCourseFee": 200.00,
        "GSTOfFullCourseFee": 214.00,
        "subsidyPerPax": 100.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 100.00
    },
    {
        "title": "Drawing on Nature - Acrylic Painting\r\n",
        "id": "CC24",
        "courseCode": "CC24",
        "organisationName": "Singapore Association for Continuing Education (SACE)",
        "type": "Short Courses",
        "category": "Media Arts & Design",
        "format": "F2F only",
        "totalDuration": 12,
        "totalSessions": 2,
        "skillsFutureEligible": true,
        "fullCourseFee": 261.60,
        "GSTOfFullCourseFee": 279.91,
        "subsidyPerPax": 200.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 61.60
    },
    {
        "title": "Journey through 4 Acts of Life with Watercolour and Pen",
        "id": "CC25",
        "courseCode": "CC25",
        "organisationName": "Singapore Association for Mental Health (SAMH)",
        "type": "Short Courses",
        "category": "Media Arts & Design",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 240.80,
        "GSTOfFullCourseFee": 257.66,
        "subsidyPerPax": 200.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 40.80
    },
    {
        "title": "Pastel Art (Japanese Pastel Nagomi Art)\r\n",
        "id": "CC26",
        "courseCode": "CC26",
        "organisationName": "\r\nLife Point",
        "type": "Short Courses",
        "category": "Media Arts & Design",
        "format": "F2F only",
        "totalDuration": 4,
        "totalSessions": 2,
        "skillsFutureEligible": false,
        "fullCourseFee": 240.80,
        "GSTOfFullCourseFee": 257.66,
        "subsidyPerPax": 200.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 40.80
    },
    {
        "title": "How to start a Home-Based Food Business\r\n",
        "id": "CC27",
        "courseCode": "CC27",
        "organisationName": "Society for WINGS (WINGS)",
        "type": "Short Courses",
        "category": "Finance & Business",
        "format": "F2F only",
        "totalDuration": 23,
        "totalSessions": 11,
        "skillsFutureEligible": true,
        "fullCourseFee": 410.00,
        "GSTOfFullCourseFee": 438.70,
        "subsidyPerPax": 300.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 110.00
    },
    {
        "title": "E-Entertainment\r",
        "id": "CC28",
        "courseCode": "CC28",
        "organisationName": "Singapore Association for Continuing Education (SACE)",
        "type": "Short Courses",
        "category": "IT & Science",
        "format": "F2F only",
        "totalDuration": 13,
        "totalSessions": 4,
        "skillsFutureEligible": true,
        "fullCourseFee": 310.00,
        "GSTOfFullCourseFee": 331.70,
        "subsidyPerPax": 300.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 10.00
    },
    {
        "title": "Cloud Storage and Sharing (Google Drive)\r",
        "id": "CC29",
        "courseCode": "CC29",
        "organisationName": "Singapore Association for Continuing Education (SACE)",
        "type": "Short Courses",
        "category": "IT & Science",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": true,
        "fullCourseFee": 210.00,
        "GSTOfFullCourseFee": 224.70,
        "subsidyPerPax": 200.00,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 10.00
    },
    {
        "title": "Build and customise your own wooden stool\r",
        "id": "CC30",
        "courseCode": "CC30",
        "organisationName": "Singapore Furniture Industries Council (SFIC)",
        "type": "Short Courses",
        "category": "Ageing & Life Skills",
        "format": "F2F only",
        "totalDuration": 3,
        "totalSessions": 1,
        "skillsFutureEligible": false,
        "fullCourseFee": 300.00,
        "GSTOfFullCourseFee": 321.00,
        "subsidyPerPax": 136.30,
        "createdDate": "19/09/2022",
        "status": "pendingApproval",
        "courseFeePerPax": 163.70
    }
];

export const fieldToTitle = {
    title: 'Title',
    courseCode: 'Course Code',
    organisationName: 'Organisation Name',
    type: 'Type',
    category: 'Category',
    format: 'Format',
    totalDuration: 'Total Duration (in hour)',
    totalSessions: 'Total Number of Sessions',
    skillsFutureEligible: 'SkillsFuture Credit Eligible',
    fullCourseFee: 'Full Course Fee Per Pax (before subsidy)',
    GSTOfFullCourseFee: 'GST of Full Course Fee Per Pax',
    createdDate: 'Submission Date',
    status: 'Status',
    remark: 'Remark',
    description: 'Description',
    objectives: 'Course Objectives',
    learningOutcomes: 'Learning Outcomes',
    topicsCovered: 'Topics Covered',
    trainingDeliveryMethods: 'Training Delivery Methods',
    trainers: 'Trainers',
    trainer: {
        name: 'Name',
        profile: 'Profile',
        source: 'Source',
        attended: 'Attended C3A Geragogy Workshop',
    },
    maxClassSize: 'Maximum Class Size',
    partA: 'Part A: Variable Costs',
    partB: 'Part A: Fixed Costs',
    trainerNo: 'No of Units',
    trainerUnitCost: 'Unit Cost',
    trainerHours: 'No of Hours',
    trainerTotal: 'Total Costs',
    facilitatorNo: 'No of Units',
    facilitatorUnitCost: 'Unit Cost',
    facilitatorHours: 'No of Hours',
    facilitatorTotal: 'Total Costs',
    manpowerNo: 'No of Units',
    manpowerUnitCost: 'Unit Cost',
    manpowerHours: 'No of Hours',
    manpowerTotal: 'Total Costs',
    manpowerRemark: 'Please elaborate',
    venueNo: 'No of Units',
    venueUnitCost: 'Unit Cost',
    venueHours: 'No of Hours',
    venueTotal: 'Total Costs',
    fullCoursePerPax: 'Full course per pax',
    publicityUnitCost: 'Unit Cost',
    publicityTotal: 'Total Costs',
    logisticUnitCost: 'Unit Cost',
    logisticTotal: 'Total Costs',
    logisticRemark: 'Please elaborate',
    transportUnitCost: 'Unit Cost',
    transportTotal: 'Total Costs',
    othersNo: 'No of Units',
    othersUnitCost: 'Unit Cost',
    othersHours: 'No of Hours',
    othersTotal: 'Total Costs',
    othersRemark: 'Please elaborate',
    ccNo: 'No of Units',
    ccUnitCost: 'Unit Cost',
    ccTotal: 'Total Costs',
    trainingNo: 'No of Units',
    trainingUnitCost: 'Unit Cost',
    trainingTotal: 'Total Costs',
    places: 'Projected number of learning places run',
    partATotal: 'Part A Subtotal',
    partBTotal: 'Part B Subtotal',
    total: 'Grand Total (Part A + Part B)',
    trainerSection: 'Trainer',
    facilitatorSection: 'Assistant Trainer/Facilitator',
    manpowerSection: 'Additional Manpower (if any)',
    publicitySection: 'Publicity and Marketing',
    venueSection: 'Venue Rental (inclusive of eletricity, Maintenance and Wifi)',
    logisticSection: 'Logistic Costs (inclusive of all activity items and teaching material, if any)',
    transportSection: 'Transport Costs',
    othersSection: 'Others (if any)',
    courseSection: 'Course Curriculum Development',
    trainingEqSection: 'Training Equipment (Fixed Assets including hardwares, iPads, laptops, AED, etc.)',
    fundingLevel: 'Funding Level',
}

export const proposalStatuses = [
    {
        name: 'pendingApproval',
        label: 'Pending Approval',
    },
    {
        name: 'approved',
        label: 'Approved',
    }, {
        name: 'pendingClarification',
        label: 'Pending Clarification',
    }, {
        name: 'rejected',
        label: 'Rejected',
    }, {
        name: 'published',
        label: 'Published',
    },
];

export const claimStatuses = [
    {
        name: 'pendingApproval',
        label: 'Pending Approval',
    },
    {
        name: 'approved',
        label: 'Approved',
    }, {
        name: 'pendingClarification',
        label: 'Pending Clarification',
    }, {
        name: 'rejected',
        label: 'Rejected',
    }
];

export const claims = [
    {
        id: 'claim1',
        courseId: '11114',
        courseCode: 'CC104',
        title: 'Course E',
        organisationName: 'Test Company',
        startDate: '06/08/2022',
        endDate: '30/09/2022',
        totalSeniors: 5,
        subsidy: {
            perPax: 800,
            totalSubsidy: 100000,
            used: 8000,
            locked: 4000,
        },
        amountToClaim: 4000,
        fullCourseFee: 1200,
        invoiceFormNo: 'er4gr-rron2',
        invoiceFormDate: '05/10/2022',
        status: 'draft',
    },
    {
        id: 'claim2',
        courseId: '11114',
        courseCode: 'CC104',
        title: 'Course E',
        organisationName: 'Test Company',
        startDate: '04/02/2022',
        endDate: '12/05/2022',
        totalSeniors: 15,
        subsidy: {
            perPax: 800,
            totalSubsidy: 100000,
            used: 12000,
            locked: 4000,
        },
        amountToClaim: 12000,
        fullCourseFee: 1200,
        invoiceFormNo: 'oiu3n-mnj2i',
        invoiceFormDate: '05/10/2022',
        status: 'approved',
    },
    {
        id: 'claim3',
        courseId: '11114',
        courseCode: 'CC104',
        title: 'Course E',
        organisationName: 'Test Company',
        startDate: '04/02/2022',
        endDate: '12/05/2022',
        totalSeniors: 10,
        subsidy: {
            perPax: 800,
            totalSubsidy: 100000,
            used: 8000,
            locked: 4000,
        },
        amountToClaim: 8000,
        fullCourseFee: 1200,
        invoiceFormNo: 'pipn3-4o2pf',
        invoiceFormDate: '05/10/2022',
        status: 'rejected',
        rejection: 'noClarification'
    },
    {
        id: 'claim4',
        courseId: '11114',
        courseCode: 'CC104',
        title: 'Course E',
        organisationName: 'Test Company',
        startDate: '04/02/2022',
        endDate: '12/05/2022',
        totalSeniors: 4,
        subsidy: {
            perPax: 800,
            totalSubsidy: 100000,
            used: 2200,
            locked: 4000,
        },
        amountToClaim: 3200,
        fullCourseFee: 1200,
        invoiceFormNo: 'qwd3d-m4ie3',
        invoiceFormDate: '05/10/2022',
        status: 'pendingClarification',
        clarification: 'Please provide attendance records for verification purpose. Thanks'
    },
    {
        id: 'claim5',
        courseId: '11114',
        courseCode: 'CC104',
        title: 'Course E',
        organisationName: 'Test Company',
        startDate: '04/02/2022',
        endDate: '12/05/2022',
        totalSeniors: 10,
        subsidy: {
            perPax: 800,
            totalSubsidy: 100000,
            used: 8000,
            locked: 4000,
        },
        fullCourseFee: 1200,
        invoiceFormNo: 'vrfeg-4t3e3',
        invoiceFormDate: '05/10/2022',
        amountToClaim: 8000,
        status: 'pendingClarification',
        clarification: 'Please provide attendance records for verification purpose. Thanks'
    },
    {
        id: 'claim6',
        courseId: '11114',
        courseCode: 'CC104',
        title: 'Course E',
        organisationName: 'Test Company',
        startDate: '04/02/2022',
        endDate: '12/05/2022',
        totalSeniors: 4,
        subsidy: {
            perPax: 800,
            totalSubsidy: 100000,
            used: 8000,
            locked: 4000,
        },
        fullCourseFee: 1200,
        invoiceFormNo: 'mmdo3-xxe34',
        invoiceFormDate: '05/10/2022',
        amountToClaim: 3200,
        status: 'pendingClarification',
        clarification: 'Please provide attendance records for verification purpose. Thanks'
    },
    {
        id: 'claim7',
        courseId: '12345',
        courseCode: 'CC105',
        title: 'Vietnamese Level 5 (Conducted Online)\n',
        organisationName: 'National University of Singapore (NUS)',
        startDate: '01/02/2022',
        endDate: '18/05/2022',
        totalSeniors: 40,
        subsidy: {
            perPax: 500,
            totalSubsidy: 100000,
            used: 8000,
            locked: 4000,
        },
        fullCourseFee: 1200,
        invoiceFormNo: 'mmdo3-xxe34',
        invoiceFormDate: '05/10/2022',
        amountToClaim: 2000,
        status: 'pendingApproval',
    },
    {
        id: 'claim8',
        courseId: '12346',
        courseCode: 'CC106',
        title: 'Build Lower Body Strength with Workout & Dance',
        organisationName: 'Singapore Association for Continuing Education (SACE)',
        startDate: '06/03/2022',
        endDate: '16/06/2022',
        totalSeniors: 13,
        subsidy: {
            perPax: 200,
            totalSubsidy: 100000,
            used: 8000,
            locked: 4000,
        },
        fullCourseFee: 1200,
        invoiceFormNo: 'mmdo3-xxe34',
        invoiceFormDate: '05/10/2022',
        amountToClaim: 2500,
        status: 'pendingApproval',
    },
];

export const claimRejections = [
    {
        id: 'noClarification',
        title: 'Clarification is requested but there is no reply from the partner.',
    },
    {
        id: 'fraud',
        title: 'Attendances are forged.'
    },
    {
        id: 'others',
        title: 'Others'
    }
]

export const claimFieldToTile = {
    title: 'Title',
    organisationName: 'Organisation',
    startDate: 'Start Date',
    endDate: 'End Date',
    fullCourseFee: 'Full Course Fee Per Pax (before subsidy)',
    GSTOfFullCourseFee: 'GST of Full Course Fee Per Pax',
    createdDate: 'Submission Date',
    subsidy: {
        perPax: 'NSA Subsidy Per Pax'
    },
    totalSeniors: 'No of Eligible Seniors',
    amountToClaim: 'Total Subsidy To Claim',
    invoiceFormNo: 'Invoice/Claim Form No',
    invoiceFormDate: 'Invoice/Claim Form Date',
};

export const courseCategories = ["Ageing & Life Skills", "Finance & Business", "Health & Wellness", "Humanities", "IT & Science", "Media, Arts & Design"];
export const courseTypes = ['Bite-Sized Courses', 'Short Courses', 'Exam Free Courses', 'Intergenerational Learning Programme'];
export const courseFormats = ["F2F only", 'F2F/Online', 'Blended'];